### ISSUE TITLE
Update Docker Compose Templates to use new EI Docker Images

### ISSUE THREAD

**Issue by imesh** [wso2/docker-ei#13]
**Description:**
Currently, Enterprise Integrator Docker Compose templates use a separate set of Dockerfiles for building its Docker images. This process can be improved by using the Enterprise Integrator Docker images built with the default Dockerfiles and using volume mounts to provide the configurations. As a result, Docker Compose templates would not need to build new product Docker images.

**Affected Product Version:**
6.1.1

**Related Issues:**
https://github.com/wso2/docker-is/issues/18, https://github.com/wso2/docker-apim/issues/63, https://github.com/wso2/docker-das/issues/3

**Comment by DilanUA** [comment]
This task is now complete for the First Milestone Docker release after recent refinements for 6.1.1.2 release.
