### ISSUE TITLE
integrator-analytics  docker-compose example is not working

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-ei#135]
**Description:**
I am try to launch the integrator-analytics docker-compose up command and I get the next error
```$ docker-compose up
Creating wso2ei-mysql ...
Creating wso2ei-mysql ... done
Creating wso2ei-analytics-worker ...
Creating wso2ei-analytics-dashboard ...
Creating wso2ei-analytics-worker
Creating wso2ei-analytics-dashboard ... done

ERROR: for wso2ei-integrator  Container "8dc840575166" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
When I see the log's container, I get the next error
```$ docker logs 8dc840575166
cp: cannot stat '/home/wso2carbon/wso2-config-volume/*': No such file or directory
```

**Suggested Labels:**
docker-compose example

**Suggested Assignees:**

**Affected Product Version:**
6.5.0

**OS, DB, other environment details and versions:**    
Windows 10
Docker Toolbox v17.10.0-ce

**Steps to reproduce:**
```
1. cd docker-ei/docker-compose/integrator-analytics
2. docker-compose up
```

**Related Issues:**

**Comment by chirangaalwis** [comment]
@oscarvesga the original issue has been fixed in https://github.com/wso2/docker-ei/pull/137.

Though just to clarify, the files with configuration changes necessary for connecting the Integrator profile with Analytics profile need to be mounted at the `/home/wso2carbon/wso2-config-volume` container location via a Docker host volume mount. Hence, for the inter-profile connections of this Docker Compose based deployment to successfully work, the particular volume mount cannot be empty.

Is there a particular reason for you to mount an empty Docker host volume to the particular location?

**Comment by oscarvesga** [comment]
@chirangaalwis I just follow the instructions in the README file (https://github.com/wso2/docker-ei/tree/master/docker-compose/integrator-analytics). I can see that the docker-compose file have the next line https://github.com/wso2/docker-ei/blob/d02ff1006891fafdc97a0ee25df470c3f1881881/docker-compose/integrator-analytics/docker-compose.yml#L30, where should I make the mount?

**Comment by chirangaalwis** [comment]
@oscarvesga the referred line mounts the `<DOCKER_GIT_REPOSITORY_HOME>/docker-compose/integrator-analytics/worker` directory (which will be a Docker host path, when you execute the Docker Compose script) to `/home/wso2carbon/wso2-config-volume` WSO2 Enterprise Integrator's Analytics Worker profile container path.

In the Docker container entry point script `docker-entrypoint.sh`, a mount at `/home/wso2carbon/wso2-config-volume` is checked for and if present, the content of the directory would be copied recursively into the original WSO2 product pack within the Docker container (please see [1]).

The configuration files mounted at the `/home/wso2carbon/wso2-config-volume` external mount point (meaning this mount is not made directly to the WSO2 product pack location within the container) in each container contain the minimum set of configuration changes required for the deployment pattern to operate successfully (in other terms, required to establish the minimum connectivity between the product profiles).

[1]: [Code segment](https://github.com/wso2/docker-ei/blob/v6.5.0.2/dockerfiles/ubuntu/analytics/worker/docker-entrypoint.sh#L31)

**Comment by oscarvesga** [comment]
@chirangaalwis so if I don't have files config in the ./worker directory, I will not start up the docker container of analitycs?

**Comment by chirangaalwis** [comment]
@oscarvesga nope. Ideally, it should start the container. This is a bug (see https://github.com/wso2/docker-ei/issues/132) which has been fixed in the most recent release of Docker and Docker Compose resources for WSO2 Integration (see https://github.com/wso2/docker-ei/releases/tag/v6.5.0.2).

**Comment by oscarvesga** [comment]
@chirangaalwis thank you, the docker-compose up command is working correctly now in the master version (6.5.0.2)
