### ISSUE TITLE
Docker resources for WSO2 Streaming Integrator v1.0.0

### ISSUE THREAD

**Issue by Aaquiff** [wso2/docker-ei#151]
**Description:**
It is required to create Docker resources for WSO2 Streaming Integrator v1.0.0.

**Sub Tasks:**
- [x] Create Alpine based Docker resources
- [x] Create CentOS based Docker resources
- [x] Create Ubuntu based Docker resources
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
For Alpine, fixed in https://github.com/wso2/docker-ei/pull/149.

**Comment by chirangaalwis** [comment]
For Ubuntu, fixed in https://github.com/wso2/docker-ei/pull/148.

**Comment by chirangaalwis** [comment]
For CentOS, fixed in https://github.com/wso2/docker-ei/pull/150.

**Comment by chirangaalwis** [comment]
Closing the issue as it is fixed in the referenced PRs.
