### ISSUE TITLE
Examples of deploy the docker-compose services in kubernetes/swarm cluster? EI-v6.5.x

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-ei#164]
**Description:**
I like to get examples of production deploy to those docker-compose file in clusters like kubernetes or swarm, especially in EI-v6.5.x

**Comment by chirangaalwis** [comment]
@oscarvesga first of all, we don't support the deployment of Docker Compose resources of any of our products in Kubernetes environments. For that purpose, we provide users with Helm Charts which package the Kubernetes resources required to deploy WSO2 products in Kubernetes environments.

For example, you may use the Helm Chart for WSO2 Integration deployment pattern 1 available at [1].

Plus, as of now, WSO2 does not provide resources for its product deployments in Docker Swarm environments.

The provided Docker Compose resources are resources required for single instance deployments of popular WSO2 product deployment patterns and are **recommended only** for evaluation purposes.

[1]: [Helm Hub](https://hub.helm.sh/charts/wso2/ei-pattern-1)

**Comment by oscarvesga** [comment]
@chirangaalwis thank you for the information
