### ISSUE TITLE
Cannot access consoles with Pattern 6

### ISSUE THREAD

**Issue by aaronscribner** [wso2/docker-ei#17]
**Description:**
Error when attempting to access the EI or Analytics console
HTTP - result - 404
HTTPS - result - 502 

**Suggested Labels:**
nginx, wso2, enterprise, integrator

**Suggested Assignees:**

**Affected Product Version:**
Whatever is in this current Pattern6 example

**OS, DB, other environment details and versions:**    
Docker on OS X

**Steps to reproduce:**
Follow the instructions in the ReadMe for Pattern6

**Comment by DilanUA** [comment]
@aaronscribner, could you let us know what JDK version you used ?

**Comment by DilanUA** [comment]
Hi aaronscribner, Thanks for your interest with the product. We have restructured the entire product repository to suit the needs of evaluation customers with a new set of docker compose deployments. Please try and let us know your feedback.
