### ISSUE TITLE
[SI - 1.0.0] Upgrade AdoptOpenJDK 8 version to the AdoptOpenJDK 11

### ISSUE THREAD

**Issue by RidmiR** [wso2/docker-ei#182]
**Description:**
Description:
The AdoptOpenJDK version needs to upgrade to the AdoptOpenJDK 11. 

Sub Tasks:

- [x]  Upgrade version in Alpine Docker resources
- [x]  Upgrade version in CentOS Docker resources
- [x]  Upgrade version in Ubuntu Docker resources
- [x]  Update Changelog

**Comment by chirangaalwis** [comment]
Fixed.
