### ISSUE TITLE
Docker resources for WSO2 Enterprise Integrator v7.1.0

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-ei#190]
**Description:**
Docker resources need to be created WSO2 Enterprise Integrator v7.1.0.

The product profiles include Micro Integrator and Streaming Integrator.

**Sub Tasks:**
- [x] Create Alpine based Docker resources
- [x] Create CentOS based Docker resources
- [x] Create Ubuntu based Docker resources
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
Fixed.
