### ISSUE TITLE
[7.1.0] Avoid Packaging MySQL JDBC Driver in WSO2 Product Docker Images 

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-ei#191]
**Description:**
It has been suggested to avoid packaging the MySQL JDBC Driver in the WSO2 product Docker images.

The original purpose of packaging this binary in Docker images was to support evaluatory deployments in container platforms such as, Kubernetes with externalized MySQL RDBMS support.

For a user who intends to use a different version of the particular connector (as opposed to what is packaged inside the image) may not be able to use the current, official WSO2 product Docker images as the base since he/she may experience version conflicts.

**Affected Product Version:**
Docker resources for WSO2  Enterprise Integrator version `v7.0.0.3` and below

**Comment by chirangaalwis** [comment]
Fixed.
