### ISSUE TITLE
[7.1.0] Docker resources for WSO2 Analytics Dashboard 1.0.0

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-ei#193]
**Description:**
Docker resources need to be created WSO2 Analytics Dashboard 1.0.0.

**Sub Tasks:**
- [x] Create Alpine based Docker resources
- [x] Create CentOS based Docker resources
- [x] Create Ubuntu based Docker resources
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
Fixed.
