### ISSUE TITLE
[6.3.0] Update dockerfiles to get resources from remote source

### ISSUE THREAD

**Issue by NishikaDeSilva** [wso2/docker-ei#226]
**Description:**
Resources such as product server pack, MySQL connector, and JDK distribution needs to be added in the files folder before building the image. This is extra overhead and thus in the latest versions, these resources are taken from remote sources. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.3.0

**Comment by chirangaalwis** [comment]
Fixed.
