### ISSUE TITLE
[7.1.0] Unable to pass parameters for server startup script

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/docker-ei#229]
**Description:**
The PR #176  has introduced a change where the args passed to the server startup script is not propagated via the `docker-entrypoint.sh`. 

**Affected Product Version:**
- MI-1.2.0
- mi-dashboard-1.2.0
- AD-1.0.0

**Sub Tasks:**
- [x] Fix Alpine based Docker resources for MI-1.2.0
- [x] Fix Alpine based Docker resources for mi-dashboard-1.2.0
- [x] Fix Alpine based Docker resources for AD-1.0.0
- [x] Code/Peer review

**Comment by chirangaalwis** [comment]
Fixed.
