### ISSUE TITLE
pull access denied for docker.wso2.com/wso2ei-analytics:6.3.0

### ISSUE THREAD

**Issue by legroen** [wso2/docker-ei#84]
Following the steps on https://wso2.com/integration/install/docker-compose/get-started/ gives me following error 

ERROR: pull access denied for docker.wso2.com/wso2ei-analytics, repository does not exist or may require 'docker login'

docker version 
Docker version 18.03.1-ce, build 9ee9f40

docker-compose version
docker-compose version 1.22.0, build f46880fe

**Steps to reproduce:**
see steps https://wso2.com/integration/install/docker-compose/get-started/

**Comment by MaximCalpacci** [comment]
Hi. Getting the same error. Any ideas?

**Comment by ThilinaManamgoda** [comment]
@MaximCalpacci Could you please mention the username you have used for docker login?

**Comment by MaximCalpacci** [comment]
@ThilinaManamgoda when running docker login command I used my WSO2 account e-mail address. I registered here - https://wso2.com/user/register

**Comment by ThilinaManamgoda** [comment]
@MaximCalpacci In order to use the Docker images hosted at docker.wso2.com registry, you must have a WSO2 subscription. You can subscribe for a free trial here - [](https://wso2.com/subscription/free-trial).

**Comment by MaximCalpacci** [comment]
@ThilinaManamgoda oh, ok, thank you!

**Comment by legroen** [comment]
Ok thx
